[package]
name = "surphury-server"
version = "0.1.0"
edition = "2021"
author = "surphury"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
mongodb = "2.2.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
