[package]
name = "surphury-server"
version = "0.1.0"
edition = "2021"
author = "surphury"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
mongodb = "2.2.1"
dotenv = "0.15.0"
ring = "0.16.20"
data-encoding = "2.3.2"
serde = { version = "1.0.137", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["json"] }
tokio = { version = "1.18.2", features = ["full"] }
sqlx = { version = "0.5.13", features = [ "runtime-tokio-rustls" ] }

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",        
    "macro-diagnostics"
]
